name: Linux CI

on:
  push:
    branches:
      - master
    tags:
      - '*'

  pull_request:
    branches:
      - master

  schedule:
    - cron: "0 6 * * 1"

jobs:
  specs:
    name: Specs
    runs-on: ubuntu-latest
    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: 1.0.0

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Make argon2
        run: cd ext && make   

      - name: Install shards
        run: shards install --ignore-crystal-version

      - name: Run specs
        run: crystal spec --error-on-warnings --error-trace

  check-format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: 1.0.0

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Check sources format
        run: crystal tool format --check

  ameba:
    name: Ameba linter
    runs-on: ubuntu-latest
    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: 1.0.0

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Make argon2
        run: cd ext && make

      - name: Install shards
        run: shards install --ignore-crystal-version

      - name: Run ameba
        run: bin/ameba